"""add ussd profile session fields

Revision ID: 213a8c0c89d0
Revises: 4767b5eac2f7
Create Date: 2026-07-13 16:36:22.300172

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '213a8c0c89d0'
down_revision = '4767b5eac2f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ussd_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_menu', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('profile_step', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('profile_data', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ussd_sessions', schema=None) as batch_op:
        batch_op.drop_column('profile_data')
        batch_op.drop_column('profile_step')
        batch_op.drop_column('current_menu')

    # ### end Alembic commands ###
