"""Add the AidToken table 

Revision ID: 2ddf2c768da4
Revises: 3ce822b6bbea
Create Date: 2026-03-02 12:24:30.870844

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ddf2c768da4'
down_revision = '3ce822b6bbea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aid_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('aid_token', sa.String(length=100), nullable=False),
    sa.Column('token_status', sa.String(length=20), nullable=True),
    sa.Column('token_issued_at', sa.DateTime(), nullable=True),
    sa.Column('distribution_session_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['distribution_session_id'], ['distribution_session.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['beneficiaries.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('aid_token')
    )
    with op.batch_alter_table('beneficiaries', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_beneficiaries_aid_token'), type_='unique')
        batch_op.drop_constraint(batch_op.f('fk_beneficiaries_distribution_session'), type_='foreignkey')
        batch_op.drop_column('token_issued_at')
        batch_op.drop_column('aid_token')
        batch_op.drop_column('token_expires_at')
        batch_op.drop_column('token_status')
        batch_op.drop_column('distribution_session_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('beneficiaries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('distribution_session_id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('token_status', sa.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('token_expires_at', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('aid_token', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('token_issued_at', sa.DATETIME(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_beneficiaries_distribution_session'), 'distribution_session', ['distribution_session_id'], ['id'])
        batch_op.create_unique_constraint(batch_op.f('uq_beneficiaries_aid_token'), ['aid_token'])

    op.drop_table('aid_tokens')
    # ### end Alembic commands ###
