"""Add the Distribution Session table

Revision ID: 3ce822b6bbea
Revises: 7d0c61be6367
Create Date: 2026-02-25 17:09:42.197589

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ce822b6bbea'
down_revision = '7d0c61be6367'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('beneficiaries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('distribution_session_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_beneficiaries_distribution_session','distribution_session', ['distribution_session_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('beneficiaries', schema=None) as batch_op:
        batch_op.drop_constraint('fk_beneficiaries_distribution_session', type_='foreignkey')
        batch_op.drop_column('distribution_session_id')

    # ### end Alembic commands ###
