"""Add the  Acive banner for users

Revision ID: 4767b5eac2f7
Revises: 4e1cfbac4625
Create Date: 2026-07-07 15:38:40.201663

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4767b5eac2f7'
down_revision = '4e1cfbac4625'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Users', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###
