"""initial_migration

Revision ID: 4e1cfbac4625
Revises: 
Create Date: 2026-06-26 12:39:21.376090

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e1cfbac4625'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('distribution_centers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('aid_center_name', sa.String(length=150), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('expiry_time', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=150), nullable=False),
    sa.Column('second_name', sa.String(length=150), nullable=False),
    sa.Column('national_id', sa.Integer(), nullable=False),
    sa.Column('contact', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('password', sa.String(length=200), nullable=False),
    sa.Column('user_type', sa.String(length=50), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('requires_password_change', sa.Boolean(), nullable=True),
    sa.Column('assigned_center_id', sa.Integer(), nullable=True),
    sa.Column('current_jti', sa.String(length=120), nullable=True),
    sa.Column('time_stamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_center_id'], ['distribution_centers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('national_id')
    )
    op.create_table('aid_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('aid_token', sa.String(length=100), nullable=False),
    sa.Column('token_status', sa.String(length=20), nullable=True),
    sa.Column('token_issued_at', sa.DateTime(), nullable=True),
    sa.Column('distribution_center_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['distribution_center_id'], ['distribution_centers.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['Users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('aid_token')
    )
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=200), nullable=False),
    sa.Column('details', sa.String(length=500), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['Users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('households',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('center_id', sa.Integer(), nullable=True),
    sa.Column('total_members', sa.Integer(), nullable=True),
    sa.Column('dependents_count', sa.Integer(), nullable=True),
    sa.Column('disability_present', sa.Boolean(), nullable=True),
    sa.Column('income_level', sa.Float(), nullable=True),
    sa.Column('is_profile_complete', sa.Boolean(), nullable=True),
    sa.Column('vulnerability_score', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['center_id'], ['distribution_centers.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['Users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('token_blocklist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jti', sa.String(length=150), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['Users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('jti')
    )
    op.create_table('ussd_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=150), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('authenticated', sa.Boolean(), nullable=True),
    sa.Column('last_active', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['Users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ussd_sessions')
    op.drop_table('token_blocklist')
    op.drop_table('households')
    op.drop_table('audit_logs')
    op.drop_table('aid_tokens')
    op.drop_table('Users')
    op.drop_table('distribution_centers')
    # ### end Alembic commands ###
