"""Add aid token fields

Revision ID: 4ed8c1f8b1c7
Revises: d0a3feb6044f
Create Date: 2026-02-13 13:05:25.082508

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ed8c1f8b1c7'
down_revision = 'd0a3feb6044f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('beneficiaries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('aid_token', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('token_status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('token_issued_at', sa.DateTime(), nullable=True))
        #batch_op.create_unique_constraint(None, ['aid_token'])
        batch_op.create_unique_constraint('uq_beneficiaries_aid_token', ['aid_token'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('beneficiaries', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('token_issued_at')
        batch_op.drop_column('token_status')
        batch_op.drop_column('aid_token')

    # ### end Alembic commands ###
