"""Add the Center Column

Revision ID: 6fb0fd224cdd
Revises: f2c4326ea64e
Create Date: 2026-06-10 13:09:47.201118

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6fb0fd224cdd'
down_revision = 'f2c4326ea64e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('distribution_session', 'distribution_centers')
    with op.batch_alter_table('Users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assigned_center_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'distribution_centers', ['assigned_center_id'], ['id'])

    with op.batch_alter_table('aid_tokens', schema=None) as batch_op:
        batch_op.add_column(sa.Column('distribution_center_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint(batch_op.f('aid_tokens_distribution_session_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'distribution_centers', ['distribution_center_id'], ['id'])
        batch_op.drop_column('distribution_session_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aid_tokens', schema=None) as batch_op:
        batch_op.add_column(sa.Column('distribution_session_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('aid_tokens_distribution_session_id_fkey'), 'distribution_session', ['distribution_session_id'], ['id'])
        batch_op.drop_column('distribution_center_id')

    with op.batch_alter_table('Users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('assigned_center_id')

    op.rename_table('distribution_centers', 'distribution_session')
    
    # ### end Alembic commands ###
