"""update table parameters

Revision ID: 7d0c61be6367
Revises: f2d516ab2d57
Create Date: 2026-02-25 15:32:11.229227

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d0c61be6367'
down_revision = 'f2d516ab2d57'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('beneficiaries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('token_expires_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('beneficiaries', schema=None) as batch_op:
        batch_op.drop_column('token_expires_at')

    # ### end Alembic commands ###
