"""Add the USSD Session Table

Revision ID: b0393c9bf076
Revises: 4ed8c1f8b1c7
Create Date: 2026-02-21 13:53:10.428904

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0393c9bf076'
down_revision = '4ed8c1f8b1c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ussd_session',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=150), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('authenticated', sa.Boolean(), nullable=True),
    sa.Column('last_active', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['beneficiaries.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id')
    )
    with op.batch_alter_table('beneficiaries', schema=None) as batch_op:
        batch_op.alter_column('aid_token',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('beneficiaries', schema=None) as batch_op:
        batch_op.alter_column('aid_token',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)

    op.drop_table('ussd_session')
    # ### end Alembic commands ###
