"""add session_id to distribution_centers and aid_tokens

Revision ID: d85b21b84bf4
Revises: 213a8c0c89d0
Create Date: 2026-07-15 17:39:28.997618

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd85b21b84bf4'
down_revision = '213a8c0c89d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Users', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['contact'])

    with op.batch_alter_table('aid_tokens', schema=None) as batch_op:
        batch_op.add_column(sa.Column('session_id', sa.String(length=36), nullable=True))

    with op.batch_alter_table('distribution_centers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_session_id', sa.String(length=36), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('distribution_centers', schema=None) as batch_op:
        batch_op.drop_column('current_session_id')

    with op.batch_alter_table('aid_tokens', schema=None) as batch_op:
        batch_op.drop_column('session_id')

    with op.batch_alter_table('Users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
