"""initial_migration

Revision ID: eeed06f6981c
Revises: 
Create Date: 2026-06-25 13:14:50.205435

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'eeed06f6981c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():

    with op.batch_alter_table('aid_tokens', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('distribution_center_id', sa.Integer(), nullable=True)
        )

        batch_op.drop_constraint(
            batch_op.f('aid_tokens_distribution_session_id_fkey'),
            type_='foreignkey'
        )

        batch_op.create_foreign_key(
            None,
            'distribution_centers',
            ['distribution_center_id'],
            ['id']
        )

        batch_op.drop_column('distribution_session_id')

    op.drop_table('distribution_session')

    with op.batch_alter_table('Users', schema=None) as batch_op:
        batch_op.create_foreign_key(
            None,
            'distribution_centers',
            ['assigned_center_id'],
            ['id']
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aid_tokens', schema=None) as batch_op:
        batch_op.add_column(sa.Column('distribution_session_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('aid_tokens_distribution_session_id_fkey'), 'distribution_session', ['distribution_session_id'], ['id'])
        batch_op.drop_column('distribution_center_id')

    with op.batch_alter_table('Users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    op.create_table('distribution_session',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('aid_center_name', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('start_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('expiry_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('distribution_session_pkey'))
    )
    # ### end Alembic commands ###
