"""Add household model

Revision ID: f2c4326ea64e
Revises: 835d134ab6e7
Create Date: 2026-06-10 10:20:05.149604

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f2c4326ea64e'
down_revision = '835d134ab6e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('distribution_centers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('aid_center_name', sa.String(length=150), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('expiry_time', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('households',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('center_id', sa.Integer(), nullable=True),
    sa.Column('total_members', sa.Integer(), nullable=True),
    sa.Column('dependents_count', sa.Integer(), nullable=True),
    sa.Column('disability_present', sa.Boolean(), nullable=True),
    sa.Column('income_level', sa.Float(), nullable=True),
    sa.Column('is_profile_complete', sa.Boolean(), nullable=True),
    sa.Column('vulnerability_score', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['center_id'], ['distribution_centers.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['Users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    # op.drop_table('distribution_session')
    # with op.batch_alter_table('aid_tokens', schema=None) as batch_op:
    #     batch_op.add_column(sa.Column('distribution_center_id', sa.Integer(), nullable=True))
    #     batch_op.drop_constraint(batch_op.f('aid_tokens_distribution_session_id_fkey'), type_='foreignkey')
    #     batch_op.create_foreign_key(None, 'distribution_centers', ['distribution_center_id'], ['id'])
    #     batch_op.drop_column('distribution_session_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aid_tokens', schema=None) as batch_op:
        batch_op.add_column(sa.Column('distribution_session_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('aid_tokens_distribution_session_id_fkey'), 'distribution_session', ['distribution_session_id'], ['id'])
        batch_op.drop_column('distribution_center_id')

    op.create_table('distribution_session',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('aid_center_name', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('start_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('expiry_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('distribution_session_pkey'))
    )
    op.drop_table('households')
    op.drop_table('distribution_centers')
    # ### end Alembic commands ###
