"""Update changes values

Revision ID: f2d516ab2d57
Revises: b0393c9bf076
Create Date: 2026-02-22 20:37:05.620090

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2d516ab2d57'
down_revision = 'b0393c9bf076'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('beneficiaries', schema=None) as batch_op:
        batch_op.alter_column('aid_token',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('beneficiaries', schema=None) as batch_op:
        batch_op.alter_column('aid_token',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)

    # ### end Alembic commands ###
